general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono" }
bold = { family = "JetBrainsMono Nerd Font Mono" }
italic = { family = "JetBrainsMono Nerd Font Mono" }
size = 9

[window]
padding.x = 3 
padding.y = 3 
decorations = "None"

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]
